@startuml
title 書き込む

autonumber "#."

actor ユーザ
participant kban.jsp
participant KbanServlet
participant KbanDAO
participant Kban
database kbanDB

ユーザ -[#green]> kban.jsp:書き込む
kban.jsp -> KbanServlet:入力
KbanServlet -> KbanDAO:生成
KbanDAO -> Kban:生成
KbanDAO -> kbanDB:書き込み
kbanDB --> KbanDAO:全データ
KbanDAO -> Kban:生成
KbanDAO --> KbanServlet:ArrayList
KbanServlet ->kban.jsp:フォワード
kban.jsp -[#green]> ユーザ:表示
@enduml